name: Social Readme
run-name: ${{ github.actor }} update Social Readme 🚀
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: elvis594/social-readme@master
        with:
          rss_hub_link: 'http://8.134.95.44:1200'
          douban_id: '186240167'
          bilibili_id: '1802901'
          zhihu_id: '594-26'