name: Social Readme
run-name: ${{ github.actor }} update Social Readme 🚀
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: elvis594/social-readme@master
        with:
          douban_id: '186240167'
          bilibili_id: '1802901'